name: Nx Java CI

env:
  NX_BATCH_MODE: true

on:
  push:

jobs:
  initial-build:
    runs-on: ubuntu-latest
    env:
      NX_CI_EXECUTION_ENV: 'initial-build'
    steps:
      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Checkout maven
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          filter: tree:0
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Maven
        shell: bash
        run: ./mvnw --errors --batch-mode --show-version org.apache.maven.plugins:maven-wrapper-plugin:3.3.2:wrapper "-Dmaven=4.0.0-rc-3"

      - name: Start CI run
        run: ./nx start-ci-run --distribute-on="5 linux-large" --stop-agents-after="verify-ci"

      - name: Build Maven distributions
        shell: bash
        run: ./nx run-many -t verify-ci --verbose

